### ISSUE TITLE
Multi-Threads Don't work?

### ISSUE THREAD

**Issue by xiaowang119** [bwvdnbro/CMacIonize#108]
The command-line parameter "--threads 16" has been used to run a task, but still only one thread was called.

**Comment by bwvdnbro** [comment]
Hi @xiaowang119,
Multithreading definitely does work, so there must be a problem with your setup. Can you please share more details about the system you are running on (in particular how many CPU cores are reported by the `nproc` command), the way you configured and compiled the code, and the simulation you are trying to run? It would also be very helpful if you could share the command line output of those different steps, as this contains a lot of information that might help diagnose the problem.

**Comment by xiaowang119** [comment]
Hi, Thanks for your reply.
The program has been commpiled according to the homepage at github. 
After export HDF5_ROOT=/name/of/the/folder, `cmake ..` and then `make` .
The `nproc` command give the result `1`.
And the command I have used to run a task is `/home/data/software/CMacIonize/build/rundir/CMacIonize --rhd --threads 16 --params my.param`.

**Comment by xiaowang119** [comment]
[my.param.txt](https://github.com/user-attachments/files/17880167/my.param.txt)
[out.txt](https://github.com/user-attachments/files/17880169/out.txt)
And the inputfile and the outlog is uploaded here.

**Comment by xiaowang119** [comment]
> Hi, Thanks for your reply. The program has been commpiled according to the homepage at github. After export HDF5_ROOT=/name/of/the/folder, `cmake ..` and then `make` . The `nproc` command give the result `1`. And the command I have used to run a task is `/home/data/software/CMacIonize/build/rundir/CMacIonize --rhd --threads 16 --params my.param`.

The reason of output `1` has been found, which origins from  the line `export OMP_NUM_THREADS=1` in `.bashrc`. But multi-threads sitll does not work well when I change it to 16.

**Comment by xiaowang119** [comment]
Thanks a lot. This problem was solved by `recompiling` the program after changing the `OMP_NUM_THREADS`.

**Comment by bwvdnbro** [comment]
Yes, that makes sense. `cmake` checks how many CPU cores are available during configuration and sets the maximum allowed number of threads based on that number. This check uses the `cmake` provided function `ProcessorCount()`, which apparently uses `OMP_NUM_THREADS` internally.

Another solution would have been to bypass that check by running `cmake` with the additional flag `-DMAX_NUMBER_OF_THREADS=16`.

Anyway, I'm glad to hear that you managed to solve the issue.
