### ISSUE TITLE
CMAKE_BUILD_TYPE not set

### ISSUE THREAD

**Issue by findesgh** [bwvdnbro/CMacIonize#23]
Doing ``mkdir build && cd build && cmake ..``  after cloning throws

     CMake Error at CMakeLists.txt:82 (if):
        if given arguments:

          "STREQUAL" "Debug"

        Unknown arguments specified

for me. May I suggest adding an additional check on whether CMAKE_BUILD_TYPE is set or not? Like so:

     if(${CMAKE_BUILD_TYPE})
       if(${CMAKE_BUILD_TYPE} STREQUAL "Debug")
         add_compiler_flag("-fsanitize=address -fno-omit-frame-pointer" OPTIONAL)
       endif(${CMAKE_BUILD_TYPE} STREQUAL "Debug")
     endif(${CMAKE_BUILDTYPE})

**Comment by bwvdnbro** [comment]
Yes. The default `CMAKE_BUILD_TYPE` should be set to `Release` as well, as that is likely the mode users want.
